function dJ_b = dJ_b(alpha_1,alpha_2,alpha_3,alpha_4,b_prox,beta_1,beta_2,beta_3,beta_4,dphi,dx,dy,dz,phi_,r_y_1,r_y_2,r_y_3,r_y_4,r_z_1,r_z_2,r_z_3,r_z_4,theta_1,theta_2,theta_3,theta_4)
%DJ_B
%    DJ_B = DJ_B(ALPHA_1,ALPHA_2,ALPHA_3,ALPHA_4,B_PROX,BETA_1,BETA_2,BETA_3,BETA_4,DPHI,DX,DY,DZ,PHI_,R_Y_1,R_Y_2,R_Y_3,R_Y_4,R_Z_1,R_Z_2,R_Z_3,R_Z_4,THETA_1,THETA_2,THETA_3,THETA_4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-May-2020 15:04:24

t2 = sin(theta_1);
t3 = cos(phi_);
t4 = sin(phi_);
t5 = sin(alpha_1);
t6 = cos(theta_1);
t7 = cos(alpha_1);
t8 = cos(beta_1);
t9 = sin(beta_1);
t10 = sin(theta_2);
t11 = sin(alpha_2);
t12 = cos(theta_2);
t13 = cos(alpha_2);
t14 = cos(beta_2);
t15 = sin(beta_2);
t16 = sin(theta_3);
t17 = sin(alpha_3);
t18 = cos(theta_3);
t19 = cos(alpha_3);
t20 = cos(beta_3);
t21 = sin(beta_3);
t22 = sin(theta_4);
t23 = sin(alpha_4);
t24 = cos(theta_4);
t25 = cos(alpha_4);
t26 = cos(beta_4);
t27 = sin(beta_4);
dJ_b = reshape([-dphi.*((b_prox.*t6.*t7-b_prox.*t2.*t5.*t8).*(r_y_1.*t4+r_z_1.*t3).*2.0-b_prox.*t2.*t9.*(r_y_1.*t3-r_z_1.*t4).*2.0)-dx.*(b_prox.*t5.*t6.*2.0+b_prox.*t2.*t7.*t8.*2.0)+dy.*(b_prox.*t6.*t7.*2.0-b_prox.*t2.*t5.*t8.*2.0)+b_prox.*dz.*t2.*t9.*2.0,0.0,0.0,0.0,0.0,-dphi.*((b_prox.*t12.*t13-b_prox.*t10.*t11.*t14).*(r_y_2.*t4+r_z_2.*t3).*2.0-b_prox.*t10.*t15.*(r_y_2.*t3-r_z_2.*t4).*2.0)-dx.*(b_prox.*t11.*t12.*2.0+b_prox.*t10.*t13.*t14.*2.0)+dy.*(b_prox.*t12.*t13.*2.0-b_prox.*t10.*t11.*t14.*2.0)+b_prox.*dz.*t10.*t15.*2.0,0.0,0.0,0.0,0.0,-dphi.*((b_prox.*t18.*t19-b_prox.*t16.*t17.*t20).*(r_y_3.*t4+r_z_3.*t3).*2.0-b_prox.*t16.*t21.*(r_y_3.*t3-r_z_3.*t4).*2.0)-dx.*(b_prox.*t17.*t18.*2.0+b_prox.*t16.*t19.*t20.*2.0)+dy.*(b_prox.*t18.*t19.*2.0-b_prox.*t16.*t17.*t20.*2.0)+b_prox.*dz.*t16.*t21.*2.0,0.0,0.0,0.0,0.0,-dphi.*((b_prox.*t24.*t25-b_prox.*t22.*t23.*t26).*(r_y_4.*t4+r_z_4.*t3).*2.0-b_prox.*t22.*t27.*(r_y_4.*t3-r_z_4.*t4).*2.0)-dx.*(b_prox.*t23.*t24.*2.0+b_prox.*t22.*t25.*t26.*2.0)+dy.*(b_prox.*t24.*t25.*2.0-b_prox.*t22.*t23.*t26.*2.0)+b_prox.*dz.*t22.*t27.*2.0],[4,4]);
