function J_a = J_a(a_x_1,a_x_2,a_x_3,a_x_4,a_y_1,a_y_2,a_y_3,a_y_4,a_z_1,a_z_2,a_z_3,a_z_4,alpha_1,alpha_2,alpha_3,alpha_4,b_prox,beta_1,beta_2,beta_3,beta_4,phi_,r_x_1,r_x_2,r_x_3,r_x_4,r_y_1,r_y_2,r_y_3,r_y_4,r_z_1,r_z_2,r_z_3,r_z_4,ra_1_1,ra_1_2,ra_1_3,ra_2_1,ra_2_2,ra_2_3,ra_3_1,ra_3_2,ra_3_3,ra_4_1,ra_4_2,ra_4_3,theta_1,theta_2,theta_3,theta_4,x_,y_,z_)
%J_A
%    J_A = J_A(A_X_1,A_X_2,A_X_3,A_X_4,A_Y_1,A_Y_2,A_Y_3,A_Y_4,A_Z_1,A_Z_2,A_Z_3,A_Z_4,ALPHA_1,ALPHA_2,ALPHA_3,ALPHA_4,B_PROX,BETA_1,BETA_2,BETA_3,BETA_4,PHI_,R_X_1,R_X_2,R_X_3,R_X_4,R_Y_1,R_Y_2,R_Y_3,R_Y_4,R_Z_1,R_Z_2,R_Z_3,R_Z_4,RA_1_1,RA_1_2,RA_1_3,RA_2_1,RA_2_2,RA_2_3,RA_3_1,RA_3_2,RA_3_3,RA_4_1,RA_4_2,RA_4_3,THETA_1,THETA_2,THETA_3,THETA_4,X_,Y_,Z_)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-May-2020 15:04:21

t2 = cos(alpha_1);
t3 = sin(theta_1);
t4 = cos(beta_1);
t5 = sin(alpha_1);
t6 = cos(theta_1);
t7 = cos(phi_);
t8 = sin(phi_);
t9 = r_z_1.*t8;
t10 = r_z_1.*t7;
t11 = r_y_1.*t8;
t12 = sin(beta_1);
t13 = x_.*2.0;
t14 = y_.*2.0;
t15 = cos(alpha_2);
t16 = sin(theta_2);
t17 = cos(beta_2);
t18 = sin(alpha_2);
t19 = cos(theta_2);
t20 = z_.*2.0;
t21 = r_z_2.*t8;
t22 = r_z_2.*t7;
t23 = r_y_2.*t8;
t24 = sin(beta_2);
t25 = cos(alpha_3);
t26 = sin(theta_3);
t27 = cos(beta_3);
t28 = sin(alpha_3);
t29 = cos(theta_3);
t30 = r_z_3.*t8;
t31 = r_z_3.*t7;
t32 = r_y_3.*t8;
t33 = sin(beta_3);
t34 = cos(alpha_4);
t35 = sin(theta_4);
t36 = cos(beta_4);
t37 = sin(alpha_4);
t38 = cos(theta_4);
t39 = r_z_4.*t8;
t40 = r_z_4.*t7;
t41 = r_y_4.*t8;
t42 = sin(beta_4);
J_a = reshape([a_x_1.*-2.0+r_x_1.*2.0+ra_1_1.*2.0+t13+b_prox.*t3.*t5.*2.0-b_prox.*t2.*t4.*t6.*2.0,a_x_2.*-2.0+r_x_2.*2.0+ra_2_1.*2.0+t13+b_prox.*t16.*t18.*2.0-b_prox.*t15.*t17.*t19.*2.0,a_x_3.*-2.0+r_x_3.*2.0+ra_3_1.*2.0+t13+b_prox.*t26.*t28.*2.0-b_prox.*t25.*t27.*t29.*2.0,a_x_4.*-2.0+r_x_4.*2.0+ra_4_1.*2.0+t13+b_prox.*t35.*t37.*2.0-b_prox.*t34.*t36.*t38.*2.0,a_y_1.*-2.0+ra_1_2.*2.0+t14+r_y_1.*t7.*2.0-r_z_1.*t8.*2.0-b_prox.*t2.*t3.*2.0-b_prox.*t4.*t5.*t6.*2.0,a_y_2.*-2.0+ra_2_2.*2.0+t14+r_y_2.*t7.*2.0-r_z_2.*t8.*2.0-b_prox.*t15.*t16.*2.0-b_prox.*t17.*t18.*t19.*2.0,a_y_3.*-2.0+ra_3_2.*2.0+t14+r_y_3.*t7.*2.0-r_z_3.*t8.*2.0-b_prox.*t25.*t26.*2.0-b_prox.*t27.*t28.*t29.*2.0,a_y_4.*-2.0+ra_4_2.*2.0+t14+r_y_4.*t7.*2.0-r_z_4.*t8.*2.0-b_prox.*t34.*t35.*2.0-b_prox.*t36.*t37.*t38.*2.0,a_z_1.*-2.0+ra_1_3.*2.0+t20+r_y_1.*t8.*2.0+r_z_1.*t7.*2.0+b_prox.*t6.*t12.*2.0,a_z_2.*-2.0+ra_2_3.*2.0+t20+r_y_2.*t8.*2.0+r_z_2.*t7.*2.0+b_prox.*t19.*t24.*2.0,a_z_3.*-2.0+ra_3_3.*2.0+t20+r_y_3.*t8.*2.0+r_z_3.*t7.*2.0+b_prox.*t29.*t33.*2.0,a_z_4.*-2.0+ra_4_3.*2.0+t20+r_y_4.*t8.*2.0+r_z_4.*t7.*2.0+b_prox.*t38.*t42.*2.0,(t9-r_y_1.*t7).*(-a_z_1+ra_1_3+t10+t11+z_+b_prox.*t6.*t12).*-2.0+(t10+t11).*(a_y_1-ra_1_2+t9-y_-r_y_1.*t7+b_prox.*t2.*t3+b_prox.*t4.*t5.*t6).*2.0,(t21-r_y_2.*t7).*(-a_z_2+ra_2_3+t22+t23+z_+b_prox.*t19.*t24).*-2.0+(t22+t23).*(a_y_2-ra_2_2+t21-y_-r_y_2.*t7+b_prox.*t15.*t16+b_prox.*t17.*t18.*t19).*2.0,(t30-r_y_3.*t7).*(-a_z_3+ra_3_3+t31+t32+z_+b_prox.*t29.*t33).*-2.0+(t31+t32).*(a_y_3-ra_3_2+t30-y_-r_y_3.*t7+b_prox.*t25.*t26+b_prox.*t27.*t28.*t29).*2.0,(t39-r_y_4.*t7).*(-a_z_4+ra_4_3+t40+t41+z_+b_prox.*t38.*t42).*-2.0+(t40+t41).*(a_y_4-ra_4_2+t39-y_-r_y_4.*t7+b_prox.*t34.*t35+b_prox.*t36.*t37.*t38).*2.0],[4,4]);
