function J_b = J_b(a_x_1,a_x_2,a_x_3,a_x_4,a_y_1,a_y_2,a_y_3,a_y_4,a_z_1,a_z_2,a_z_3,a_z_4,alpha_1,alpha_2,alpha_3,alpha_4,b_prox,beta_1,beta_2,beta_3,beta_4,phi_,r_x_1,r_x_2,r_x_3,r_x_4,r_y_1,r_y_2,r_y_3,r_y_4,r_z_1,r_z_2,r_z_3,r_z_4,ra_1_1,ra_1_2,ra_1_3,ra_2_1,ra_2_2,ra_2_3,ra_3_1,ra_3_2,ra_3_3,ra_4_1,ra_4_2,ra_4_3,theta_1,theta_2,theta_3,theta_4,x_,y_,z_)
%J_B
%    J_B = J_B(A_X_1,A_X_2,A_X_3,A_X_4,A_Y_1,A_Y_2,A_Y_3,A_Y_4,A_Z_1,A_Z_2,A_Z_3,A_Z_4,ALPHA_1,ALPHA_2,ALPHA_3,ALPHA_4,B_PROX,BETA_1,BETA_2,BETA_3,BETA_4,PHI_,R_X_1,R_X_2,R_X_3,R_X_4,R_Y_1,R_Y_2,R_Y_3,R_Y_4,R_Z_1,R_Z_2,R_Z_3,R_Z_4,RA_1_1,RA_1_2,RA_1_3,RA_2_1,RA_2_2,RA_2_3,RA_3_1,RA_3_2,RA_3_3,RA_4_1,RA_4_2,RA_4_3,THETA_1,THETA_2,THETA_3,THETA_4,X_,Y_,Z_)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    13-May-2020 15:04:23

t2 = sin(alpha_1);
t3 = sin(theta_1);
t4 = cos(alpha_1);
t5 = cos(beta_1);
t6 = cos(theta_1);
t7 = cos(phi_);
t8 = sin(phi_);
t9 = sin(beta_1);
t10 = sin(alpha_2);
t11 = sin(theta_2);
t12 = cos(alpha_2);
t13 = cos(beta_2);
t14 = cos(theta_2);
t15 = sin(beta_2);
t16 = sin(alpha_3);
t17 = sin(theta_3);
t18 = cos(alpha_3);
t19 = cos(beta_3);
t20 = cos(theta_3);
t21 = sin(beta_3);
t22 = sin(alpha_4);
t23 = sin(theta_4);
t24 = cos(alpha_4);
t25 = cos(beta_4);
t26 = cos(theta_4);
t27 = sin(beta_4);
J_b = reshape([(b_prox.*t4.*t6-b_prox.*t2.*t3.*t5).*(a_y_1-ra_1_2-y_-r_y_1.*t7+r_z_1.*t8+b_prox.*t3.*t4+b_prox.*t2.*t5.*t6).*-2.0-(b_prox.*t2.*t6+b_prox.*t3.*t4.*t5).*(-a_x_1+r_x_1+ra_1_1+x_+b_prox.*t2.*t3-b_prox.*t4.*t5.*t6).*2.0+b_prox.*t3.*t9.*(-a_z_1+ra_1_3+z_+r_y_1.*t8+r_z_1.*t7+b_prox.*t6.*t9).*2.0,0.0,0.0,0.0,0.0,(b_prox.*t12.*t14-b_prox.*t10.*t11.*t13).*(a_y_2-ra_2_2-y_-r_y_2.*t7+r_z_2.*t8+b_prox.*t11.*t12+b_prox.*t10.*t13.*t14).*-2.0-(b_prox.*t10.*t14+b_prox.*t11.*t12.*t13).*(-a_x_2+r_x_2+ra_2_1+x_+b_prox.*t10.*t11-b_prox.*t12.*t13.*t14).*2.0+b_prox.*t11.*t15.*(-a_z_2+ra_2_3+z_+r_y_2.*t8+r_z_2.*t7+b_prox.*t14.*t15).*2.0,0.0,0.0,0.0,0.0,(b_prox.*t18.*t20-b_prox.*t16.*t17.*t19).*(a_y_3-ra_3_2-y_-r_y_3.*t7+r_z_3.*t8+b_prox.*t17.*t18+b_prox.*t16.*t19.*t20).*-2.0-(b_prox.*t16.*t20+b_prox.*t17.*t18.*t19).*(-a_x_3+r_x_3+ra_3_1+x_+b_prox.*t16.*t17-b_prox.*t18.*t19.*t20).*2.0+b_prox.*t17.*t21.*(-a_z_3+ra_3_3+z_+r_y_3.*t8+r_z_3.*t7+b_prox.*t20.*t21).*2.0,0.0,0.0,0.0,0.0,(b_prox.*t24.*t26-b_prox.*t22.*t23.*t25).*(a_y_4-ra_4_2-y_-r_y_4.*t7+r_z_4.*t8+b_prox.*t23.*t24+b_prox.*t22.*t25.*t26).*-2.0-(b_prox.*t22.*t26+b_prox.*t23.*t24.*t25).*(-a_x_4+r_x_4+ra_4_1+x_+b_prox.*t22.*t23-b_prox.*t24.*t25.*t26).*2.0+b_prox.*t23.*t27.*(-a_z_4+ra_4_3+z_+r_y_4.*t8+r_z_4.*t7+b_prox.*t26.*t27).*2.0],[4,4]);
